# Generated by Django 5.1.5 on 2025-01-31 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="название привычки",
                    ),
                ),
                (
                    "place",
                    models.CharField(max_length=75, verbose_name="место привычки"),
                ),
                ("time", models.TimeField(verbose_name="время дня привычки")),
                (
                    "action",
                    models.CharField(max_length=75, verbose_name="действие привычки"),
                ),
                (
                    "is_nice_habit",
                    models.BooleanField(verbose_name="признак приятной привычки"),
                ),
                (
                    "frequency_number",
                    models.PositiveIntegerField(verbose_name="Количество раз"),
                ),
                (
                    "frequency_unit",
                    models.CharField(
                        choices=[
                            ("minutes", "минуты"),
                            ("hours", "часы"),
                            ("days", "дни"),
                        ],
                        default="days",
                        max_length=10,
                        verbose_name="Единицы измерения",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(verbose_name="Длительность действия"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Публичная"),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
            },
        ),
    ]
