# Generated by Django 5.1.5 on 2025-01-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(max_length=75, verbose_name="Действие привычки"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_nice_habit",
            field=models.BooleanField(verbose_name="Признак приятной привычки"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Название привычки"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(max_length=75, verbose_name="Место привычки"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(verbose_name="Время дня привычки"),
        ),
    ]
